/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.learning.domain.avdl;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface CompanyProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"CompanyProtocol\",\"namespace\":\"com.learning.domain.avdl\",\"types\":[{\"type\":\"record\",\"name\":\"Company\",\"fields\":[{\"name\":\"companyName\",\"type\":\"string\"},{\"name\":\"year\",\"type\":\"int\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends CompanyProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.learning.domain.avdl.CompanyProtocol.PROTOCOL;
  }
}